language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
before_install:
- pip install codecov
install:
- pip install .
script:
- coverage run tests/all_tests.py
after_success:
- coverage combine
- codecov
deploy:
  provider: pypi
  user: travis.rrze-hpc
  password:
    secure: "BmriGgM1lyCOn8FBqiGj2GloNTCu1ztev/z/6pwyiPe2CzGN5Juv/55Ib8JNUZezs9luWlaSpv3/x4nBkyAkBJB4YM3o/2x3/lxVb+L0BPM10fpgtdex9wCv55wyrQ0zZXAyatsG5wASk1REkQfp+H+BUPEq6FejQs4YfCuA3Qb3kdI1zMl4AYlAyz03ykwyWZNRF2SIehWNGoxvmbg7hmbTIPuWSGLeXNeS8Dl9ykCANKWLknEpIjYKMqde/Sm7Xcq82ueMcSDSqbMdWnNDwmLG6LLVIr3UBqibopyEvmgCkgtR6I5ib7u0JL2z6QPtNlQ9OHFhpmuKPjUtjcPuHJ3HPJGKnlZhBwV9JH+mE7/pFSFqcjJDsXIv7YKVi6MiKgwWeVWllS8O0p1PjbebviA/CBxEU1t/OSRwKnQmYDkNJZ1e9IYpiz6yY8Nf5C7yRtdM2Na6kwaWvNInkYDTeALdokW0uvxWTzTzNAysM7fyAzw6mLpBH10Dkkbg3sW3ZZzT6d4vBT7usEfGICV+bz9oZP5EOldcGRltUFrh3dY3OO9XTypiZa3+dYT+/hLcnPY6F9zZy2BYh7qNeEuK4cjYbQTuNHjchWy6OrkHBexcB1JrqT/lVir0HxLevFzv8qSLpwVMK6hhzOC5DSJk9LddNZ8b1Amu0qfdtThIOOY="
  on:
    repo: RRZE-HPC/pycachesim
