language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
before_install:
- pip install codecov
install:
- pip install .
script:
- coverage run tests/all_tests.py
after_success:
- coverage combine
- codecov
deploy:
  provider: pypi
  user: __token__
  password:
    secure: eYGLOFjt9Of22vnoWLkJfY1D5KiwnloaDpsRi1vseW5e96XDr4zevX132cfYzk7+IHUUQnDIQcxd5BeYgBHnO1Eftnv2Wfjv9rl70ZXnjg0/mhDdXffo1wZyHk3L/FKgnGbf6p8/MXAhIi1PlNeSVQ0T7E8QpXVyresD48xXxOXRit1XYGO//48FFSq+mYF9a6K3fCaUSWuw9FV++UnpgNFDnHso0X2inCrqJ3hSFhvuBrntUunJ2M6yTyvyG/gJNooVV60X5DMME/XLX7fGyewjHhtNlKOsFKTgDNc7+bhI7AJcxkmQkfv579TOKDHnBt9mHqIAGPyu040xXwKSzjGeE/bQdj0WjD4AR+zmm95w+y89IemYoaygRRsbcRGkApXaPIo+6FLhmhLmRd94ACKT1bGeHIFvOm209MbCZj/wTHs5SVwbeOuDZqOe85siO/ddrZLfGysBJVk3erwDRvaqZ6Imzo/NcDx13IlwmZHqOheQmtWf+G/kT4KaQJjA2lEpUB9TyNieaiTvSQ1ZeuFvycb17Tq8nYLmox0hCz2qEtG2Bj0BSZnC5PH9U5VaaWHywul67VltzvQTFYaggLhIEp2+xj/oYtLNwFUCwBdFz8Iratz1cK+lRqGSsu1ktC2Za4hZYKtwfZgDAmqksyp5SJAo37yMS6kSfAYqXEY=
  skip_existing: true
  skip_cleanup: true
  on:
    repo: RRZE-HPC/pycachesim
    tag: true
